"""create resumes table

Revision ID: 1bd7bc63dfa8
Revises: a3d134ee3d15
Create Date: 2026-07-05 14:04:35.030201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1bd7bc63dfa8'
down_revision: Union[str, Sequence[str], None] = 'a3d134ee3d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native enums, managed explicitly so downgrade also drops the types.
resume_file_type = postgresql.ENUM("pdf", "docx", name="resume_file_type")
resume_extraction_status = postgresql.ENUM(
    "pending", "processing", "completed", "failed",
    name="resume_extraction_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum types first; create_type=False on the columns prevents
    # create_table from trying to create them a second time.
    resume_file_type.create(op.get_bind(), checkfirst=True)
    resume_extraction_status.create(op.get_bind(), checkfirst=True)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', postgresql.ENUM('pdf', 'docx', name='resume_file_type', create_type=False), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='resume_extraction_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_file_type'), 'resumes', ['file_type'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_status'), 'resumes', ['status'], unique=False)
    op.create_index(op.f('ix_resumes_stored_filename'), 'resumes', ['stored_filename'], unique=True)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_stored_filename'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_file_type'), table_name='resumes')
    op.drop_table('resumes')
    # Drop the enum types once no table references them.
    resume_extraction_status.drop(op.get_bind(), checkfirst=True)
    resume_file_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
