"""create connector runs table

Revision ID: 310801ab4e96
Revises: 68e339e3211d
Create Date: 2026-07-04 15:35:49.557560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '310801ab4e96'
down_revision: Union[str, Sequence[str], None] = '68e339e3211d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native enum, managed explicitly so downgrade also drops the type.
connector_run_status = postgresql.ENUM(
    "running", "success", "failed", name="connector_run_status"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first; create_type=False on the column prevents
    # create_table from trying to create it a second time.
    connector_run_status.create(op.get_bind(), checkfirst=True)
    op.create_table('connector_runs',
    sa.Column('connector_name', sa.String(length=100), nullable=False),
    sa.Column('status', postgresql.ENUM('running', 'success', 'failed', name='connector_run_status', create_type=False), server_default='running', nullable=False),
    sa.Column('fetched_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingested_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_runs_connector_name'), 'connector_runs', ['connector_name'], unique=False)
    op.create_index(op.f('ix_connector_runs_finished_at'), 'connector_runs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_connector_runs_id'), 'connector_runs', ['id'], unique=False)
    op.create_index(op.f('ix_connector_runs_started_at'), 'connector_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_connector_runs_status'), 'connector_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_runs_status'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_started_at'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_id'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_finished_at'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_connector_name'), table_name='connector_runs')
    op.drop_table('connector_runs')
    # Drop the enum type once no table references it.
    connector_run_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
