"""job alerts partial unique index on live rows

Revision ID: 68e339e3211d
Revises: 8cb89b7bac04
Create Date: 2026-07-04 15:18:09.964830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e339e3211d'
down_revision: Union[str, Sequence[str], None] = '8cb89b7bac04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_job_alerts_user_saved_search'), 'job_alerts', type_='unique')
    op.create_index('uq_job_alerts_user_saved_search', 'job_alerts', ['user_id', 'saved_search_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_job_alerts_user_saved_search', table_name='job_alerts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_job_alerts_user_saved_search'), 'job_alerts', ['user_id', 'saved_search_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
