"""create job alerts table

Revision ID: 8cb89b7bac04
Revises: b89e23a87cb0
Create Date: 2026-07-04 12:57:36.213643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8cb89b7bac04'
down_revision: Union[str, Sequence[str], None] = 'b89e23a87cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native enum, managed explicitly so downgrade also drops the type.
job_alert_frequency = postgresql.ENUM(
    "instant", "daily", "weekly", name="job_alert_frequency"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first; create_type=False on the column prevents
    # create_table from trying to create it a second time.
    job_alert_frequency.create(op.get_bind(), checkfirst=True)
    op.create_table('job_alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('saved_search_id', sa.UUID(), nullable=False),
    sa.Column('frequency', postgresql.ENUM('instant', 'daily', 'weekly', name='job_alert_frequency', create_type=False), server_default='daily', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_match_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'saved_search_id', name='uq_job_alerts_user_saved_search')
    )
    op.create_index(op.f('ix_job_alerts_frequency'), 'job_alerts', ['frequency'], unique=False)
    op.create_index(op.f('ix_job_alerts_id'), 'job_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_job_alerts_is_active'), 'job_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_alerts_next_run_at'), 'job_alerts', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_job_alerts_saved_search_id'), 'job_alerts', ['saved_search_id'], unique=False)
    op.create_index(op.f('ix_job_alerts_user_id'), 'job_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_alerts_user_id'), table_name='job_alerts')
    op.drop_index(op.f('ix_job_alerts_saved_search_id'), table_name='job_alerts')
    op.drop_index(op.f('ix_job_alerts_next_run_at'), table_name='job_alerts')
    op.drop_index(op.f('ix_job_alerts_is_active'), table_name='job_alerts')
    op.drop_index(op.f('ix_job_alerts_id'), table_name='job_alerts')
    op.drop_index(op.f('ix_job_alerts_frequency'), table_name='job_alerts')
    op.drop_table('job_alerts')
    # Drop the enum type once no table references it.
    job_alert_frequency.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
