"""saved searches partial unique index on live rows

Revision ID: b89e23a87cb0
Revises: 568fcbf14f40
Create Date: 2026-07-04 12:49:21.840652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89e23a87cb0'
down_revision: Union[str, Sequence[str], None] = '568fcbf14f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_saved_searches_user_name'), 'saved_searches', type_='unique')
    op.create_index('uq_saved_searches_user_name', 'saved_searches', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_saved_searches_user_name', table_name='saved_searches', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_saved_searches_user_name'), 'saved_searches', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
